fmt:
    npx @biomejs/biome@2.5.5 format --write

check:
    npx typescript@7 -p ./server_scripts/jsconfig.json
    npx typescript@7 -p ./client_scripts/jsconfig.json
    npx typescript@7 -p ./startup_scripts/jsconfig.json

update-server:
    rsync -vhP -r . mc_server:/var/home/juh9870/mc_server/current/data/kubejs
    rsync -vhP -r ../config mc_server:/var/home/juh9870/mc_server/current/data/config