// priority: 0

ClientEvents.generateAssets('after_mods', (event) => {
  const t1 = [];
  const t2 = [];
  const t3 = [];
  const t4 = [
    'l2artifacts:luck_clover_necklace_4',
    'l2artifacts:luck_clover_body_4',
    'l2artifacts:luck_clover_bracelet_4',
    'l2artifacts:luck_clover_belt_4',
  ];
  const t5 = [];
  for (const artifact of [
    'random',
    'random_set',
    'artifact_experience',
    'stat_container',
    'boost_main',
    'boost_sub',
    'gambler_head',
    'gambler_necklace',
    'gambler_body',
    'gambler_bracelet',
    'gambler_belt',
    'berserker_head',
    'berserker_necklace',
    'berserker_body',
    'berserker_bracelet',
    'berserker_belt',
    'archer_head',
    'archer_necklace',
    'archer_body',
    'archer_bracelet',
    'archer_belt',
    'saint_head',
    'saint_necklace',
    'saint_body',
    'saint_bracelet',
    'saint_belt',
    'perfection_head',
    'perfection_necklace',
    'perfection_body',
    'perfection_bracelet',
    'perfection_belt',
    'damocles_head',
    'protection_head',
    'froze_head',
    'froze_necklace',
    'froze_body',
    'froze_bracelet',
    'froze_belt',
    'executor_head',
    'executor_necklace',
    'executor_body',
    'executor_bracelet',
    'executor_belt',
    'physical_head',
    'physical_necklace',
    'physical_body',
    'physical_bracelet',
    'physical_belt',
    'wrath_head',
    'wrath_necklace',
    'wrath_body',
    'wrath_bracelet',
    'wrath_belt',
    'photosynthesis_head',
    'vampire_head',
    'vampire_necklace',
    'vampire_body',
    'vampire_bracelet',
    'vampire_belt',
    'sun_block_head',
    'gluttony_head',
    'gluttony_necklace',
    'gluttony_body',
    'gluttony_bracelet',
    'gluttony_belt',
    'fury_of_fallen_head',
    'fury_of_fallen_necklace',
    'fury_of_fallen_body',
    'fury_of_fallen_bracelet',
    'fury_of_fallen_belt',
    'ancient_scroll_head',
    'ancient_scroll_necklace',
    'ancient_scroll_body',
    'ancient_scroll_bracelet',
    'ancient_scroll_belt',
    'abyss_medal_head',
    'abyss_medal_necklace',
    'abyss_medal_body',
    'abyss_medal_bracelet',
    'abyss_medal_belt',
    'long_shooter_head',
    'long_shooter_necklace',
    'long_shooter_bracelet',
    'long_shooter_belt',
    'cell_head',
    'cell_necklace',
    'cell_body',
    'cell_bracelet',
    'cell_belt',
    'flesh_head',
    'flesh_necklace',
    'flesh_body',
    'flesh_bracelet',
    'flesh_belt',
    'fungus_head',
    'fungus_necklace',
    'fungus_body',
    'fungus_bracelet',
    'fungus_belt',
    'gilded_head',
    'gilded_necklace',
    'gilded_body',
    'gilded_bracelet',
    'gilded_belt',
    'poisonous_head',
    'poisonous_necklace',
    'poisonous_body',
    'poisonous_bracelet',
    'poisonous_belt',
    'slimy_head',
    'slimy_body',
    'slimy_belt',
    'thermal_head',
    'thermal_necklace',
    'thermal_body',
    'thermal_bracelet',
    'thermal_belt',
    'mage_head',
    'mage_necklace',
    'mage_body',
    'mage_bracelet',
    'mage_belt',
    'pirate_head',
    'pirate_necklace',
    'pirate_body',
    'pirate_bracelet',
    'pirate_belt',
  ]) {
    t1.push('l2artifacts:' + artifact + '_1');
    t2.push('l2artifacts:' + artifact + '_2');
    t3.push('l2artifacts:' + artifact + '_3');
    t4.push('l2artifacts:' + artifact + '_4');
    t5.push('l2artifacts:' + artifact + '_5');
  }

  EMI.add(event, 'kubejs', 'common_artifacts', /** @type {RegistryTypes.Item[]} */ (t1));
  EMI.add(event, 'kubejs', 'rare_artifacts', /** @type {RegistryTypes.Item[]} */ (t2));
  EMI.add(event, 'kubejs', 'epic_artifacts', /** @type {RegistryTypes.Item[]} */ (t3));
  EMI.add(event, 'kubejs', 'legendary_artifacts', /** @type {RegistryTypes.Item[]} */ (t4));
  EMI.add(event, 'kubejs', 'godly_artifacts', /** @type {RegistryTypes.Item[]} */ (t5));
  EMI.add(event, 'kubejs', 'legendary_materials', ['#l2complements:l2c_legendary']);
});
